version: "3"

services:
    redis:
        image: redis:alpine
        volumes:
        - redis-data:/data
    app:
        build: ./app
        image: app:${APP_VERSION:-latest}
        ports:
        - ${APP_PORT:-5000}:5000
        volumes:
        - ./app/app.py:/app/app.py
        environment:
            FLASK_DEBUG: 1

volumes:
    redis-data: {}
